-- CreateTable
CREATE TABLE "rafs" (
    "id" SERIAL NOT NULL,
    "Production" TEXT,
    "Item number" TEXT,
    "ModuleID" TEXT,
    "Nama Produk" TEXT,
    "PIC Process" TEXT,
    "PIC Packing" TEXT,
    "Site" TEXT,
    "Warehouse" TEXT,
    "Quantity" DOUBLE PRECISION,
    "Started" DOUBLE PRECISION,
    "Report as finished" DOUBLE PRECISION,
    "Tanggal" TIMESTAMP(3),
    "BOMConsump" DOUBLE PRECISION,
    "BOMProposal" DOUBLE PRECISION,
    "Qty Adjust" DOUBLE PRECISION,
    "Started2" TIMESTAMP(3),
    "Ended" TIMESTAMP(3),
    "Status" TEXT,
    "Total Loss" DOUBLE PRECISION,
    "Hours" DOUBLE PRECISION,
    "Man Hours" DOUBLE PRECISION,
    "Result Viskositas" DOUBLE PRECISION,
    "Result SolidContent" DOUBLE PRECISION,
    "Result pH" DOUBLE PRECISION,
    "Pool" TEXT,
    "Mesin" TEXT,
    "Production Type" TEXT,
    "Total Material Consumption" DOUBLE PRECISION,
    "BOM number" TEXT,

    CONSTRAINT "rafs_pkey" PRIMARY KEY ("id")
);
